[package]
name = "rcalc"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
clap = { version = "3.1.5", features = ["derive"] }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
  "llvm13-0",
] }
peg = "0.8.0"
