[package]
name = "rcalc"
version = "0.1.0"
edition = "2021"

[features]
jit = ["inkwell"]

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
inkwell = { version = "0.1.1", features = ["llvm15-0"], optional = true }
peg = "0.8.1"
