[package]
name = "rcalc"
version = "0.1.0"
edition = "2021"

[features]
jit = ["inkwell"]

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
inkwell = { version = "0.2.0", features = ["llvm16-0"], optional = true }
peg = "0.8.1"
