[package]
name = "rcalc"
version = "0.1.0"
edition = "2021"

[features]
jit = ["inkwell"]

[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
  "llvm13-0",
], optional = true }
peg = "0.8.0"
